repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
    - id: check-docstring-first
    - id: debug-statements
    - id: name-tests-test
    - id: check-executables-have-shebangs
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-json
    - id: check-symlinks
    - id: check-merge-conflict
    - id: check-ast
    - id: detect-private-key
    - id: fix-byte-order-marker
    - id: pretty-format-json

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.17
  hooks:
    - id: terraform-fmt

- repo: https://github.com/asottile/setup-cfg-fmt
  rev: v1.19.0
  hooks:
    - id: setup-cfg-fmt
