apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/pipelines
  - ../../base/tasks
  - ../../base/triggers
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: tkn-ssh-credentials
    files:
      - creds/id_rsa
  - name: tkn-docker-credentials
    files:
      - creds/.dockerconfigjson
    type: kubernetes.io/dockerconfigjson
  - name: tkn-github-secret
    type: Opaque
    literals:
      - secretToken=
  - name: tkn-github-token
    type: Opaque
    literals:
      - secretToken=
patchesJson6902:
  - target:
      version: v1
      kind: Secret
      name: github-secret
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          tekton.dev/git-0: github.com
