apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- tkn-dashboards.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: prod-tkn-ssh-credentials
  files:
  - creds/id_rsa