name: build-push

env:
  NAME: nginx-web
  IMAGE: gregnrobinson/bcgov-nginx-demo
  WORKDIR: ./demo/nginx

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      NAME:
        required: true
        type: string
      IMAGE:
        required: true
        type: string
      WORKDIR:
        required: true
        type: string
    secrets:
      IMAGE_REGISTRY_USER:
        required: true
      IMAGE_REGISTRY_PASSWORD:
        required: true
jobs:
  build-push:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.IMAGE_REGISTRY_USER }}
        password: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
    - name: Build
      working-directory: ${{ inputs.WORKDIR }}
      run: >
        docker buildx build
        --platform=linux/amd64,linux/arm64
        -t ${{ inputs.IMAGE }}:${{ env.GITHUB_SHA_SHORT }}
        --output=type=image,push=true
        ${GITHUB_WORKSPACE}/${{ inputs.WORKDIR }}
    - name: Trivy Vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ inputs.IMAGE }}:${{ env.GITHUB_SHA_SHORT }}
        format: table
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: os,library
        severity: CRITICAL
    - id: latest
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        repository: ${{ github.repository }}
        excludes: prerelease, draft
    - name: Tag Push Latest
      working-directory: ${{ inputs.WORKDIR }}
      run: >
        docker buildx build
        --platform=linux/amd64,linux/arm64
        -t ${{ inputs.IMAGE }}:${{ env.GITHUB_SHA_SHORT }}
        -t ${{ inputs.IMAGE }}:${{ steps.latest.outputs.release }}
        -t ${{ inputs.IMAGE }}:latest
        --output=type=image,push=true
        ${GITHUB_WORKSPACE}/${{ inputs.WORKDIR }}
