name: owasp-base-scan
env:
  SCAN_TYPE: 'full' # Accepted values are base and full.
  TARGET_URL: http://www.itsecgames.com/
  DURATION: '2'
  MAX_DURATION: '5'
on:
  workflow_dispatch:
jobs:
  zap_base:
    runs-on: ubuntu-latest
    name: ZAP Base Scan
    steps:
      - name: ZAP Baseline Scan
        if: ${{ env.SCAN_TYPE == 'base' }}
        uses: zaproxy/action-baseline@@v0.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: ${{ env.TARGET_URL }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -d -T ${{ env.MAX_DURATION }} -m ${{ env.DURATION }}'
          issue_title: OWAP Baseline
      - name: ZAP Full Scan
        if: ${{ env.SCAN_TYPE == 'full' }}
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: ${{ env.TARGET_URL }}
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -d'
          issue_title: OWASP Full