name: sonar-scan-repo

env:
  ORG: ci-testing
  PROJECT_KEY: pipeline-templates
  URL: https://sonarcloud.io
  WORKDIR: .

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 9 * * *'
jobs:
  sonar-scan:
    name: Sonar Scan
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: warchant/setup-sonar-scanner@v3
      - name: Run Sonar Scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sonar-scanner
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
             -Dsonar.organization=${{ env.ORG }}
             -Dsonar.host.url=${{ env.URL }}
             -Dsonar.projectKey=${{ env.PROJECT_KEY }}
