name: sonar-scan-repo

env:
  ORG: ci-testing
  PROJECT_KEY: bcgov-pipeline-templates
  URL: https://sonarcloud.io
  WORKDIR: ./demo/flask-web

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ORG:
        required: true
        type: string
      PROJECT_KEY:
        required: true
        type: string
      URL:
        required: true
        type: string
    secrets:
      SONAR_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true
  push:
  schedule:
    - cron: '0 9 * * *'
jobs:
  sonar-scan:
    name: Sonar Scan
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: warchant/setup-sonar-scanner@v3
      - name: Run Sonar Scanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sonar-scanner
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
             -Dsonar.organization=${{ inputs.ORG }}
             -Dsonar.host.url=${{ inputs.URL }}
             -Dsonar.projectKey=${{ inputs.PROJECT_KEY }}
             -Dsonar.exclusions=**/*.java
             -Dsonar.sourceEncoding=UTF-8
